name: 'Contributor Labeler'
description: 'Output an array of the users in CODEOWNERS'
inputs:
  path: # location for codeowners file
    description: 'Alternative location for the CODEOWNERS file'
    required: false
outputs:
  owners: # id of output
    description: 'Array of owners'
runs:
  using: 'node12'
  main: 'dist/index.js'
