name: 'Contributor Labeler'
description: 'Add the contributor label to a PR if the author is not in the CODEOWNERS file'
inputs:
  author:  # id of input
    description: 'Who to check for'
    required: true
    default: 'user'
  path: # location for codeowners file
    description: 'Alternative location for the CODEOWNERS file'
    required: false
outputs:
  is_contributor: # id of output
    description: 'Is the author a contributor?'
runs:
  using: 'node12'
  main: 'dist/index.js'
  # main: 'index.js'