name: 'Contributor Labeler'
description: 'Determine if the author is in the CODEOWNERS file'
inputs:
  author:  # id of input
    description: 'Who to check for'
    required: true
    default: 'user'
  path: # location for codeowners file
    description: 'Alternative location for the CODEOWNERS file'
    required: false
outputs:
  inCodeOwners: # id of output
    description: 'Is the author in CODEOWNERS?'
runs:
  using: 'node12'
  main: 'dist/index.js'
  # main: 'index.js'