name: 'Output Codeowners'
description: 'Output an array of the users in CODEOWNERS'
inputs:
  owners_location: # location for codeowners file
    description: 'Location for the CODEOWNERS file if it is not in the root of the repo'
    required: false
outputs:
  owners: # id of output
    description: 'Array of owners'
runs:
  using: 'node12'
  # main: 'dist/index.js'
  main: '../index.js'
branding:
  icon: 'award'  
  color: 'green'
