name: Contributor Labeler v0.11
on:
  pull_request:
    types: [opened]

jobs:
  contributor_labeler_job:
    runs-on: ubuntu-latest
    name: If author is not in CODEOWNERS, add contributor label
    steps:
      - name: Debug
        run: echo "v0.11"
        
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: "contributor-labeler"

      - name: Contributor Labeler Action
        uses: ./ # Uses an action in the root directory
        id: labeler
        with:
          author: ${{ github.actor }}
          path: "contributor-labeler"

      - name: Get the output
        run: |
          echo "The output is ${{ steps.labeler.outputs.inCodeOwners }}"
          echo "The true and eval is ${{ true && steps.labeler.outputs.inCodeOwners }}"
          echo "The false and eval is ${{ false && steps.labeler.outputs.inCodeOwners }}"

      - name: Add Label
        if: ${{ true && steps.labeler.outputs.inCodeOwners }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: contributor
          github_token: "${{ secrets.GITHUB_TOKEN }}"
