name: Contributor Labeler v0.16
on:
  pull_request:
    types: [opened]

jobs:
  contributor_labeler_job:
    runs-on: ubuntu-latest
    name: If author is not in CODEOWNERS, add contributor label
    steps:
      - name: Version
        run: echo "v0.16"
        
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #   path: "contributor-labeler"

      - name: Contributor Labeler Action
        uses: ./ # Uses an action in the root directory
        id: labeler
        with:
          author: ${{ github.actor }}
          path: "contributor-labeler"
          
      - name: Get the output
        run: echo "The output is ${{ steps.labeler.outputs.inCodeOwners }}"
          
      - name: Add Label
        # invert the boolean since we only want to add the label
        # when the author is _not_ in CODEOWNERS
        if: ${{ steps.labeler.outputs.inCodeOwners == false }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: contributor
          github_token: "${{ secrets.GITHUB_TOKEN }}"
