name: Contributor Labeler v4.3
on:
  pull_request:
    types: [opened]

jobs:
  contributor_labeler_job:
    runs-on: ubuntu-latest
    name: A job to say something
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Contributor Labeler Action
        uses: ./ # Uses an action in the root directory
        id: labeler
        with:
          author: ${{ github.actor }}
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The output is ${{ steps.labeler.outputs.is_contributor }}"